# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4299dc59259e7b2af70dfe993c63164b"
name = "primesupplements-admin-actions"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_orders"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
