
api_version = "2025-04"

# Admin Print Extension (Invoice + AWB with checkboxes)
[[extensions]]
name = "admin-print"
handle = "admin-print"
type = "ui_extension"
uid = "admin-print-uid-001"

[[extensions.targeting]]
module = "./src/AdminPrintExtension.tsx"
target = "admin.order-details.print-action.render"


# Valid extension targets:
# - admin.order-details.print-action.render
# - admin.order-index.selection-print-action.render
# - admin.product-details.print-action.render
# - admin.product-index.selection-print-action.render
