
api_version = "2025-04"

# Combined Print Action Extension (Invoice + AWB)
[[extensions]]
name = "order-documents-print"
handle = "order-documents-print"
type = "ui_extension"
uid = "order-documents-print-uid-001"

[[extensions.targeting]]
module = "./src/OrderDocumentsPrintExtension.tsx"
target = "admin.order-details.print-action.render"


# Valid extension targets:
# - admin.order-details.print-action.render
# - admin.order-index.selection-print-action.render
# - admin.product-details.print-action.render
# - admin.product-index.selection-print-action.render
