
api_version = "2025-04"

# AWB Print Extension (Shipping Label Only)
[[extensions]]
name = "Print AWB"
handle = "awb-print"
type = "ui_extension"
uid = "awb-print-uid-001"

[[extensions.targeting]]
module = "./src/AdminPrintExtension.tsx"
target = "admin.order-details.print-action.render"


# Valid extension targets:
# - admin.order-details.print-action.render
# - admin.order-index.selection-print-action.render
# - admin.product-details.print-action.render
# - admin.product-index.selection-print-action.render
